spring:
   jmx:
      enabled: false
   application:
     name: Lego Bricklink Inventory
   datasource:
      # database-key-name: rasppi5-01-lego-sandbox
      database-key-name: rasppi5-01-lego-prod-legacy
      hikari:
         connection-timeout: 10000
         idle-timeout: 30000
         connection-test-query: SELECT 1
         initialization-fail-timeout: 10000
         auto-commit: false
         login-timeout: 10000
         minimum-idle: 5
         maximum-pool-size: 5
         validation-timeout: 10000
         pool-name: site5-mysql-jdbc-pool
   main:
      web-application-type: none
   config:
      import: file:/dev/config/bricklink/bricklink-client-api-keys.yml, file:/dev/config/bricklink/bricklink-web.yml, file:/dev/config/database/database-configuration.yml

bricklink:
   rest:
      uri: https://api.bricklink.com/api/store/v1
   web:
      pool:
         default-max-per-route: 20
         max-per-route: 20
         max-total: 50
      urls:
        login-logout: "https://www.bricklink.com/ajax/renovate/loginandout.ajax"
        imgAdd: "https://www.bricklink.com/imgAdd.asp"
        inventoryDetail: "https://www.bricklink.com/inventory_detail.asp"
        inventoryUpdate: "https://www.bricklink.com/inventory_detail.asp"
        wantedListDownload: "https://www.bricklink.com/files/clone/wanted/downloadXML.file"
        catalogDownload: "https://www.bricklink.com/catalogDownload.asp?a=a"

logging:
   level:
      root: INFO
#      com.vattima.lego.data.ibatis.mapper: WARN
#      net.bricklink.data: WARN
#      org.springframework.jdbc: WARN
#      org.springframework: DEBUG
#      org.mybatis: WARN
#      com.gargoylesoftware: ERROR
#      com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter: OFF
#      com.zaxxer: WARN
#      org.apache: WARN
#      feign: WARN
#      sun: WARN
#      okhttp3: WARN

lego:
   sheet:
      dataStoreDir: c:/users/tvatt/.credentials/sheets.googleapis.com-java-quickstart
      clientSecretDir: /client_secret.json
      id: 1KegFWxww3v6qWn6lfg8PWb-X8Ipc8Y3Asq7l6subgq4
      workbook: By BOX
      #workbook: By BOX, by NUMBER
      range: A2:F
